from pathlib import Path
p=Path('/home/ubuntu/banking-fintech-roadmap/client/src/pages/Home.tsx')
s=p.read_text()
s=s.replace('const { user, loading, isAuthenticated } = useAuth();', 'const { user, loading, isAuthenticated, logout } = useAuth();')
s=s.replace('<div className="sidebar-footer"><button className="settings-link"', '<div className="sidebar-footer"><button className="settings-link"')
s=s.replace('<div className="save-note"><CircleCheck size={14} /> {saveWorkspaceMutation.isPending ? "syncing…" : "synced to account"}</div></div>', '<div className="save-note"><CircleCheck size={14} /> {saveWorkspaceMutation.isPending ? "syncing…" : "synced to account"}</div><button className="logout-link" onClick={() => logout().catch(() => notify("Could not sign out. Try again."))}><UserRound size={15} /> Sign out</button></div>')
s=s.replace('Your personalized operating system for moving toward {profile.targetJob} in {profile.targetField}, shaped around {profile.interests || "the skills and interests you choose"}.', 'Your personalized operating system for moving toward {profile.targetJob} in {profile.targetField}, shaped around {profile.interests || "the skills and interests you choose"}.')
s=s.replace('A workspace for your next move', 'A general data-career workspace for your next move')
s=s.replace('Sign in to set a target field, choose a role, and build a learning system around the work you actually want.', 'Sign in to choose a data-career direction, target role, and interests. The workspace then builds a practical learning system around the work you actually want.')
s=s.replace('Continue with Manus', 'Sign in with Manus')
# Insert the recommendation component before Roadmap.
marker='function Roadmap({ profile }: { profile: CareerProfile }) {'
component='''function SkillRecommendations({ profile }: { profile: CareerProfile }) {\n  const recommendSkills = trpc.skills.recommend.useMutation();\n  const [recommendations, setRecommendations] = useState<Array<{ skill: string; category: string; why: string; practice: string; priority: string; week: number }>>([]);\n  const generate = () => {\n    recommendSkills.mutate({ role: profile.targetJob || "Data professional", field: profile.targetField || "Any industry", interests: profile.interests, experience: profile.experience, goals: profile.goals }, { onSuccess: (result) => setRecommendations(result.recommendations) });\n  };\n  return <section className="recommendation-panel panel"><div className="recommendation-head"><div><span className="kicker">AI CAREER SIGNAL</span><h3>Skills worth learning next</h3><p>Recommendations for <strong>{profile.targetJob || "your target role"}</strong> in <strong>{profile.targetField || "your target field"}</strong>, balanced across technical data work and career evidence.</p></div><button className="primary-button compact" onClick={generate} disabled={recommendSkills.isPending}><Sparkles size={15} /> {recommendSkills.isPending ? "Thinking…" : recommendations.length ? "Refresh recommendations" : "Recommend skills"}</button></div>{recommendations.length > 0 && <div className="recommendation-grid">{recommendations.map((item) => <article className="recommendation-card" key={`${item.skill}-${item.week}`}><div className="recommendation-card-top"><span>{item.category}</span><b>{item.priority}</b></div><h4>{item.skill}</h4><p>{item.why}</p><div className="recommendation-practice"><strong>Practice</strong><span>{item.practice}</span></div><small>Suggested week {String(item.week).padStart(2, "0")}</small></article>)}</div>}</section>;\n}\n\n'''
if component not in s: s=s.replace(marker, component+marker)
s=s.replace('    <div className="dashboard-grid"><div className="panel next-panel">', '    <SkillRecommendations profile={profile} />\n    <div className="dashboard-grid"><div className="panel next-panel">', 1)
p.write_text(s)
print('patched AI recommendations, sign-in copy, and logout control')
